name: tourease
description: "TourEase - Tour Booking Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  go_router: ^14.6.2
  image_picker: ^1.1.2
  http: ^1.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  qr_flutter: ^4.1.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo_pro.png
  android_12:
    image: assets/images/app_logo_pro.png
    color: "#ffffff"
  web: false
